# Generated by Django 2.2.16 on 2020-10-28 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_name', models.CharField(max_length=200)),
                ('launch_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Pending', 'Pending'), ('Archived', 'Archived')], default='Pending', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('description', models.TextField()),
                ('type_task', models.CharField(choices=[('Survey', 'Survey'), ('Discussion', 'Discussion'), ('Diary', 'Diary')], default='Survey', max_length=10)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tile')),
            ],
        ),
    ]
